{
 "title": "Content Switching Virtual Server Overview",
 "tags": [ "netscaler" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ns_instance", "label": "NetScaler Instance", "query": "label_values(ns_instance)" },
   {
    "name": "cs_virtual_server",
    "label": "CS Virtual Server",
    "query": "query_result(cs_virtual_servers_state{ns_instance=~\"$ns_instance\"} and cs_virtual_servers_state{virtual_server!~\".*httpredir.*$\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "State",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(cs_virtual_servers_state{ns_instance=~\"$ns_instance\",virtual_server=~\"$cs_virtual_server\"})"
    }
   ]
  },
  {
   "title": "Client Connections",
   "type": "singlestat",
   "description": "Number of current client connections on a specific virtual server",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cs_virtual_servers_current_client_connections{ns_instance=~\"$ns_instance\",virtual_server=~\"$cs_virtual_server\"})"
    }
   ]
  },
  {
   "title": "Established Connections",
   "type": "singlestat",
   "description": "Number of client connections in ESTABLISHED state.",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cs_virtual_servers_established_connections{ns_instance=~\"$ns_instance\",virtual_server=~\"$cs_virtual_server\"})"
    }
   ]
  },
  {
   "title": "Server Connections",
   "type": "singlestat",
   "description": "Number of current connections to the actual servers behind the specific virtual server",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(cs_virtual_servers_current_server_connections{ns_instance=~\"$ns_instance\",virtual_server=~\"$cs_virtual_server\"})"
    }
   ]
  },
  {
   "title": "Hits",
   "type": "singlestat",
   "description": "Total virtual server hits",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cs_virtual_servers_total_hits{ns_instance=~\"$ns_instance\",virtual_server=~\"$cs_virtual_server\"})"
    }
   ]
  },
  {
   "title": "Deferred Requests",
   "type": "singlestat",
   "description": "Number of deferred request on this vserver",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cs_virtual_servers_deferred_requests{ns_instance=~\"$ns_instance\",virtual_server=~\"$cs_virtual_server\"})"
    }
   ]
  },
  {
   "title": "Hits",
   "type": "graph",
   "description": "Number of hits/second to a specific virtual server",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "hits/second" }
   ],
   "targets": [
    {
     "expr": "rate(cs_virtual_servers_total_hits{virtual_server=~\"$cs_virtual_server\",ns_instance=~\"$ns_instance\"}[$__interval])",
     "legendFormat": "Virtual Server Hit Rate - {{virtual_server}} - {{ns_instance}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Number of current client connections on a specific virtual server",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "none", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "cs_virtual_servers_current_client_connections{ns_instance=~\"$ns_instance\",virtual_server=~\"$cs_virtual_server\"}",
     "legendFormat": "Client Connections - {{virtual_server}} - {{ns_instance}}"
    },
    {
     "expr": "cs_virtual_servers_current_server_connections{ns_instance=~\"$ns_instance\",virtual_server=~\"$cs_virtual_server\"}",
     "legendFormat": "Server Connections - {{virtual_server}} - {{ns_instance}}"
    }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "graph",
   "description": "Request & response kbps from a specific virtual server",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(cs_virtual_servers_total_request_bytes{virtual_server=~\"$cs_virtual_server\",ns_instance=~\"$ns_instance\"}[$__interval]) * 8",
     "legendFormat": "Request Transfer Rate - {{virtual_server}} on {{ns_instance}}"
    },
    {
     "expr": "rate(cs_virtual_servers_total_response_bytes{virtual_server=~\"$cs_virtual_server\",ns_instance=~\"$ns_instance\"}[$__interval]) * 8",
     "legendFormat": "Response Transfer Rate - {{virtual_server}} on {{ns_instance}}"
    }
   ]
  },
  {
   "title": "Requests & Responses",
   "type": "graph",
   "description": "Number of requets/responses per second from a specific virtual server",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cs_virtual_servers_total_requests{virtual_server=~\"$cs_virtual_server\",ns_instance=~\"$ns_instance\"}[$__interval])",
     "legendFormat": "Requests - {{virtual_server}} on {{ns_instance}}"
    },
    {
     "expr": "rate(cs_virtual_servers_total_responses{virtual_server=~\"$cs_virtual_server\",ns_instance=~\"$ns_instance\"}[$__interval])",
     "legendFormat": "Responses - {{virtual_server}} on {{ns_instance}}"
    }
   ]
  },
  {
   "title": "Packets Sent/Received",
   "type": "graph",
   "description": "Total number of packets sent/received",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cs_virtual_servers_total_packets_received{virtual_server=~\"$cs_virtual_server\",ns_instance=~\"$ns_instance\"}[$__interval])",
     "legendFormat": "Received - {{virtual_server}} on {{ns_instance}}"
    },
    {
     "expr": "rate(cs_virtual_servers_total_packets_sent{virtual_server=~\"$cs_virtual_server\",ns_instance=~\"$ns_instance\"}[$__interval])",
     "legendFormat": "Sent - {{virtual_server}} on {{ns_instance}}"
    }
   ]
  },
  {
   "title": "Invalid Requests",
   "type": "graph",
   "description": "Number invalid requests/responses on this vserver",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cs_virtual_servers_number_invalid_request_response{virtual_server=~\"$cs_virtual_server\",ns_instance=~\"$ns_instance\"}[$__interval])",
     "legendFormat": "Invalid Requests - {{virtual_server}} - {{ns_instance}}"
    },
    {
     "expr": "rate(cs_virtual_servers_number_invalid_request_response_dropped{virtual_server=~\"$cs_virtual_server\",ns_instance=~\"$ns_instance\"}[$__interval])",
     "legendFormat": "Invalid Requests Dropped - {{virtual_server}} - {{ns_instance}}"
    }
   ]
  },
  {
   "title": "Problem Virtual Servers",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "cs_virtual_servers_state{ns_instance=~\"$ns_instance\",virtual_server=~\"$cs_virtual_server\"} != 1"
    }
   ]
  }
 ]
}