{
 "title": "GSLB Virtual Server Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ns_instance", "label": "NetScaler Instance", "query": "label_values(ns_instance)" },
   {
    "name": "gslb_virtual_server",
    "label": "GSLB Virtual Server",
    "query": "query_result(gslb_virtual_servers_health{ns_instance=~\"$ns_instance\"} and gslb_virtual_servers_health{virtual_server!~\".*httpredir.*$\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Health",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(gslb_virtual_servers_health{ns_instance=~\"$ns_instance\",virtual_server=~\"$gslb_virtual_server\"})"
    }
   ]
  },
  {
   "title": "Active Services",
   "type": "singlestat",
   "description": "Number of active services bound to a specific virtual server",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(gslb_virtual_servers_active_services{ns_instance=~\"$ns_instance\",virtual_server=~\"$gslb_virtual_server\"})"
    }
   ]
  },
  {
   "title": "Inactive Services",
   "type": "singlestat",
   "description": "Number of inactive services bound to a specific virtual server",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(gslb_virtual_servers_inactive_services{ns_instance=~\"$ns_instance\",virtual_server=~\"$gslb_virtual_server\"})"
    }
   ]
  },
  {
   "title": "Total Hits",
   "type": "singlestat",
   "description": "Total virtual server hits",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(gslb_virtual_servers_total_hits{ns_instance=~\"$ns_instance\",virtual_server=~\"$gslb_virtual_server\"})"
    }
   ]
  },
  {
   "title": "Hits",
   "type": "graph",
   "description": "Virtual server hits",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(gslb_virtual_servers_total_hits{virtual_server=~\"$gslb_virtual_server\",ns_instance=~\"$ns_instance\"}[$__interval])",
     "legendFormat": "{{virtual_server}}"
    }
   ]
  },
  {
   "title": "Active vs Inactive Services",
   "type": "graph",
   "description": "Number of active services bound to a specific virtual server",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gslb_virtual_servers_active_services{virtual_server=~\"$gslb_virtual_server\",ns_instance=~\"$ns_instance\"}",
     "legendFormat": "Active Services - {{virtual_server}}"
    },
    {
     "expr": "gslb_virtual_servers_inactive_services{virtual_server=~\"$gslb_virtual_server\",ns_instance=~\"$ns_instance\"}",
     "legendFormat": "Inactive Services - {{virtual_server}}"
    }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "graph",
   "description": "Request & response kbps from a specific virtual server",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(gslb_virtual_servers_total_request_bytes{virtual_server=~\"$gslb_virtual_server\",ns_instance=~\"$ns_instance\"}[$__interval]) * 8",
     "legendFormat": "Requests {{virtual_server}} - {{ns_instance}}"
    },
    {
     "expr": "rate(gslb_virtual_servers_total_response_bytes{virtual_server=~\"$gslb_virtual_server\",ns_instance=~\"$ns_instance\"}[$__interval]) * 8",
     "legendFormat": "Responses {{virtual_server}} - {{ns_instance}}"
    }
   ]
  },
  {
   "title": "Requests & Responses",
   "type": "graph",
   "description": "Number of requets/responses per second from a specific virtual server",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gslb_virtual_servers_total_requests{virtual_server=~\"$gslb_virtual_server\",ns_instance=~\"$ns_instance\"}[$__interval])",
     "legendFormat": "Requests {{virtual_server}} - {{ns_instance}}"
    },
    {
     "expr": "rate(gslb_virtual_servers_total_responses{virtual_server=~\"$gslb_virtual_server\",ns_instance=~\"$ns_instance\"}[$__interval])",
     "legendFormat": "Responses {{virtual_server}} - {{ns_instance}}"
    }
   ]
  },
  {
   "title": "Client Connections",
   "type": "graph",
   "description": "Number of current client connections on a specific virtual server",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gslb_virtual_servers_current_client_connections{virtual_server=~\"$gslb_virtual_server\",ns_instance=~\"$ns_instance\"}",
     "legendFormat": "{{virtual_server}}"
    }
   ]
  },
  {
   "title": "Server Connections",
   "type": "graph",
   "description": "Number of current connections to the actual servers behind the specific virtual server",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gslb_virtual_servers_current_server_connections{virtual_server=~\"$gslb_virtual_server\",ns_instance=~\"$ns_instance\"}"
    }
   ]
  },
  {
   "title": "Problem Virtual Servers",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "gslb_virtual_servers_health{ns_instance=~\"$ns_instance\",virtual_server=~\"$gslb_virtual_server\"} != 100"
    }
   ]
  }
 ]
}