{
 "title": "GSLB Service Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ns_instance", "label": "NetScaler Instance", "query": "label_values(ns_instance)" },
   {
    "name": "gslb_service",
    "label": "GSLB Service",
    "query": "query_result(gslb_service_state{ns_instance=~\"$ns_instance\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "State",
   "type": "singlestat",
   "description": "Current state of the service",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(gslb_service_state{ns_instance=~\"$ns_instance\",service=~\"$gslb_service\"})"
    }
   ]
  },
  {
   "title": "Load",
   "type": "singlestat",
   "description": "Load on the service that is calculated from the bound load based monitor",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(gslb_service_current_load{ns_instance=~\"$ns_instance\",service=~\"$gslb_service\"})"
    }
   ]
  },
  {
   "title": "Client Connections",
   "type": "singlestat",
   "description": "Number of current client connections",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(gslb_service_current_client_connections{ns_instance=~\"$ns_instance\",service=~\"$gslb_service\"})"
    }
   ]
  },
  {
   "title": "Total Hits",
   "type": "singlestat",
   "description": "Number of times that the service has been provided",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(gslb_service_virtual_server_service_hits{ns_instance=~\"$ns_instance\",service=~\"$gslb_service\"})"
    }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "graph",
   "description": "Request & response kbps from a specific service",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (service)(rate(gslb_service_total_request_bytes{service=~\"$gslb_service\",ns_instance=~\"$ns_instance\"}[$__interval]) * 8)",
     "legendFormat": "Requests {{service}}"
    },
    {
     "expr": "sum by (service)(rate(gslb_service_total_response_bytes{service=~\"$gslb_service\",ns_instance=~\"$ns_instance\"}[$__interval]) * 8)",
     "legendFormat": "Responses {{service}}"
    }
   ]
  },
  {
   "title": "Requests & Responses",
   "type": "graph",
   "description": "Number of requets/responses per second from a specific virtual server",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service)(rate(gslb_service_total_requests{service=~\"$gslb_service\",ns_instance=~\"$ns_instance\"}[$__interval]))",
     "legendFormat": "Requests {{service}}"
    },
    {
     "expr": "sum by (service)(rate(gslb_service_total_responses{virtual_server=~\"$gslb_service\",ns_instance=~\"$ns_instance\"}[$__interval]))",
     "legendFormat": "Responses {{service}}"
    }
   ]
  },
  {
   "title": "Client Connections",
   "type": "graph",
   "description": "Number of current client connections",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gslb_service_current_client_connections{service=~\"$gslb_service\",ns_instance=~\"$ns_instance\"}",
     "legendFormat": "{{service}} on {{ns_instance}}"
    }
   ]
  },
  {
   "title": "Server Connections",
   "type": "graph",
   "description": "Number of current connections to the actual servers",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gslb_service_current_server_connections{service=~\"$gslb_service\",ns_instance=~\"$ns_instance\"}",
     "legendFormat": "{{service}} on {{ns_instance}}"
    }
   ]
  },
  {
   "title": "Problem Services",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "gslb_service_state{ns_instance=~\"$ns_instance\",service=~\"$gslb_service\"} != 1"
    }
   ]
  }
 ]
}