{
 "title": "NetScaler - Client Connections",
 "tags": [ "netscaler" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "ns_instance", "label": "NetScaler Instance", "query": "label_values(ns_instance)" }
  ]
 },
 "panels": [
  {
   "title": "Virtual Servers - Total Client Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Client Connections" }
   ],
   "targets": [
    {
     "expr": "(virtual_servers_current_client_connections{ns_instance=~\"$ns_instance\"} != 0)",
     "legendFormat": "{{virtual_server}}"
    }
   ]
  },
  {
   "title": "Virtual Server Hit Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(virtual_servers_total_hits{ns_instance=~\"$ns_instance\"}[$interval])) != 0",
     "legendFormat": "{{virtual_server}}"
    }
   ]
  },
  {
   "title": "Virtual Server Request & Response Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(rate(virtual_servers_total_request_bytes{ns_instance=~\"$ns_instance\"}[$interval]) + rate(virtual_servers_total_response_bytes{ns_instance=~\"$ns_instance\"}[$interval])) != 0",
     "legendFormat": "{{virtual_server}}"
    }
   ]
  }
 ]
}