{
 "title": "Instance Overview",
 "tags": [ "netscaler" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ns_instance", "label": "NetScaler Instance", "query": "label_values(ns_instance)" }
  ]
 },
 "panels": [
  {
   "title": "Current Bandwidth",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "Mbits",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(total_received_mb{ns_instance=~\"$ns_instance\"}[$__interval]) + rate(total_transmit_mb{ns_instance=~\"$ns_instance\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Bandwidth Usage",
   "type": "singlestat",
   "description": "NetScaler model - reflects the bandwidth available",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(rate(total_received_mb{ns_instance=~\"$ns_instance\"}[$__interval]) + rate(total_transmit_mb{ns_instance=~\"$ns_instance\"}[$__interval])) / model_id{ns_instance=~\"$ns_instance\"} * 100"
    }
   ]
  },
  {
   "title": "Packet CPU Usage",
   "type": "singlestat",
   "description": "Current CPU utilisation for packet engines, excluding management",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "pkt_cpu_usage{ns_instance=\"$ns_instance\"}"
    }
   ]
  },
  {
   "title": "Management CPU Usage",
   "type": "singlestat",
   "description": "Current CPU utilisation for management",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "mgmt_cpu_usage{ns_instance=\"$ns_instance\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "description": "Current memory utilisation",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "mem_usage{ns_instance=\"$ns_instance\"}"
    }
   ]
  },
  {
   "title": "Used space in /var",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "var_partition_usage{ns_instance=\"$ns_instance\"}"
    }
   ]
  },
  {
   "title": "Megabits per second",
   "type": "graph",
   "description": "Number of Megabits transmitted/received by the NetScaler appliance per second",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "expr": "rate(total_transmit_mb{ns_instance=~\"$ns_instance\"}[$__interval])",
     "legendFormat": "Transmitted"
    },
    {
     "expr": "rate(total_received_mb{ns_instance=~\"$ns_instance\"}[$__interval])",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Bandwidth Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(total_transmit_mb{ns_instance=~\"$ns_instance\"}[$__interval]) / model_id{ns_instance=~\"$ns_instance\"} * 100",
     "legendFormat": "Transmit"
    },
    {
     "expr": "rate(total_received_mb{ns_instance=~\"$ns_instance\"}[$__interval]) / model_id{ns_instance=~\"$ns_instance\"} * 100",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Data Received by Interface",
   "type": "graph",
   "description": "Number of bits/s received per second by specific interfaces",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(interfaces_received_bytes{ns_instance=\"$ns_instance\"}[$__interval]) * 8",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Data Transmitted by Interface",
   "type": "graph",
   "description": "Number of bits/s transmitted per second by specific interfaces",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(interfaces_transmitted_bytes{ns_instance=\"$ns_instance\"}[$__interval]) * 8",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Packets Received by Interface",
   "type": "graph",
   "description": "Number of packets received per second by specific interfaces",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(interfaces_received_packets{ns_instance=\"$ns_instance\"}[$__interval])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Packets Transmitted by Interface",
   "type": "graph",
   "description": "Number of packets transmitted per second by specific interfaces",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(interfaces_transmitted_packets{ns_instance=\"$ns_instance\"}[$__interval])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "HTTP requests/responses per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Per second" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests{ns_instance=\"$ns_instance\"}[$__interval])",
     "legendFormat": "HTTP Request Rate - {{$ns_instance}}"
    },
    {
     "expr": "rate(http_responses{ns_instance=\"$ns_instance\"}[$__interval])",
     "legendFormat": "HTTP Response Rate - {{$ns_instance}}"
    }
   ]
  },
  {
   "title": "TCP Client Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tcp_current_client_connections{ns_instance=\"$ns_instance\"}",
     "legendFormat": "TCP Client Connections"
    },
    {
     "expr": "tcp_current_client_connections_established{ns_instance=\"$ns_instance\"}",
     "legendFormat": "TCP Established Client Connections"
    }
   ]
  },
  {
   "title": "TCP Server Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tcp_current_server_connections{ns_instance=\"$ns_instance\"}",
     "legendFormat": "TCP Server Connections"
    },
    {
     "expr": "tcp_current_server_connections_established{ns_instance=\"$ns_instance\"}",
     "legendFormat": "TCP Established Server Connections"
    }
   ]
  },
  {
   "title": "Packet Engine CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "pkt_cpu_usage{ns_instance=\"$ns_instance\"}"
    }
   ]
  },
  {
   "title": "Management CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mgmt_cpu_usage{ns_instance=\"$ns_instance\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mem_usage{ns_instance=\"$ns_instance\"}",
     "legendFormat": "Memory Usage %"
    }
   ]
  }
 ]
}