{
 "title": "Problems",
 "tags": [ "netscaler" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "ns_instance",
    "label": "NetScaler Instance",
    "query": "virtual_servers_active_services{}"
   },
   {
    "name": "virtual_server",
    "label": "Virtual Servers",
    "query": "query_result(virtual_servers_health{ns_instance=~\"$ns_instance\"} != 100 and virtual_servers_health{virtual_server!~\".*httpredir.*$\"} and virtual_servers_health{virtual_server!~\".*_AP.*$\"} and virtual_servers_health{virtual_server!~\"$exclude\"})"
   },
   {
    "name": "service_group",
    "label": "Service Group",
    "query": "query_result(servicegroup_state{ns_instance=~\"$ns_instance\"} != 1 and servicegroup_state{servicegroup!~\".*_AP.*$\"})"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "query_result(service_state{ns_instance=~\"$ns_instance\"} != 1)"
   },
   {
    "name": "ap_virtual_server",
    "label": "Virtual Servers",
    "query": "query_result(virtual_servers_health{ns_instance=~\"$ns_instance\"} == 0 and virtual_servers_health{virtual_server!~\".*httpredir.*$\"} and virtual_servers_health{virtual_server=~\".*_AP$\"})"
   },
   { "name": "exclude", "label": "Exclude", "query": "/.*-dev.*/" },
   {
    "name": "gslb_virtual_server",
    "label": "GSLB Virtual Servers",
    "query": "query_result(gslb_virtual_servers_health{ns_instance=~\"$ns_instance\"}  != 100 and gslb_virtual_servers_health{virtual_server!~\"$exclude\"})"
   },
   {
    "name": "gslb_service",
    "label": "GSLB Service",
    "query": "query_result(gslb_service_state{ns_instance=~\"$ns_instance\"}  != 1)"
   },
   {
    "name": "cs_virtual_server",
    "label": "CS Virtual Server",
    "query": "query_result(cs_virtual_servers_state{ns_instance=~\"$ns_instance\"}  != 1)"
   }
  ]
 },
 "panels": [
  { "title": "CS Virtual Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$cs_virtual_server",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "repeat": "cs_virtual_server",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cs_virtual_servers_state{ns_instance=~\"$ns_instance\", virtual_server=~\"$cs_virtual_server\"}"
    }
   ]
  },
  { "title": "GSLB Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "$gslb_service",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "repeat": "gslb_service",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "gslb_service_state{ns_instance=~\"$ns_instance\", service=~\"$gslb_service\"}"
    }
   ]
  },
  { "title": "GSLB Virtual Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "$gslb_virtual_server",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "repeat": "gslb_virtual_server",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "gslb_virtual_servers_health{ns_instance=~\"$ns_instance\", virtual_server=~\"$gslb_virtual_server\"}"
    }
   ]
  },
  { "title": "Virtual Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "$virtual_server",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "repeat": "virtual_server",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "virtual_servers_health{ ns_instance=~\"$ns_instance\", virtual_server=~\"$virtual_server\"}"
    }
   ]
  },
  { "title": "Active/Passive Virtual Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "$ap_virtual_server",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 17 },
   "repeat": "ap_virtual_server",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "virtual_servers_health{ ns_instance=~\"$ns_instance\", virtual_server=~\"$ap_virtual_server\"}"
    }
   ]
  },
  { "title": "Service Groups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "$service_group",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 21 },
   "repeat": "service_group",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(servicegroup_state{ns_instance=~\"$ns_instance\",servicegroup=~\"$service_group\"}) / count(servicegroup_state{ns_instance=~\"$ns_instance\",servicegroup=~\"$service_group\"}) * 100"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "$service",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4.8, "x": 0, "y": 25 },
   "repeat": "service",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "service_state{ns_instance=~\"$ns_instance\", service=~\"$service\"}"
    }
   ]
  }
 ]
}