{
 "title": "Service Overview",
 "tags": [ "netscaler" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "ns_instance", "label": "NetScaler Instance", "query": "label_values(ns_instance)" },
   {
    "name": "service",
    "label": "Service",
    "query": "query_result(service_active_transactions{ns_instance=~\"$ns_instance\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "description": "Current state of the service",
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(service_state{ns_instance=~\"$ns_instance\",service=~\"$service\"}) / count(service_state{ns_instance=~\"$ns_instance\",service=~\"$service\"}) * 100"
    }
   ]
  },
  {
   "title": "Active Transactions",
   "type": "singlestat",
   "description": "Number of active transactions handled by this service. (Including those in the surge queue.) Active Transaction means number of transactions currently served by the server including those waiting in the SurgeQ",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(service_active_transactions{ns_instance=~\"$ns_instance\",service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Current Reuse Pool",
   "type": "singlestat",
   "description": "Number of requests in the idle queue/reuse pool.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(service_current_reuse_pool{ns_instance=~\"$ns_instance\",service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Surge Queue",
   "type": "singlestat",
   "description": "Number of requests in the surge queue",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(service_surge_count{ns_instance=~\"$ns_instance\",service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Load",
   "type": "singlestat",
   "description": "Load on the service that is calculated from the bound load based monitor",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(service_current_load{ns_instance=~\"$ns_instance\",service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "singlestat",
   "description": "Total number of requests received on this service",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(service_total_requests{ns_instance=~\"$ns_instance\",service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Total Responses",
   "type": "singlestat",
   "description": "Total number of responses received on this service",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(service_total_responses{ns_instance=~\"$ns_instance\",service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Total Request Bytes",
   "type": "singlestat",
   "description": "Total number of request bytes received on this service",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(service_total_request_bytes{ns_instance=~\"$ns_instance\",service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Total Response Bytes",
   "type": "singlestat",
   "description": "Total number of response bytes received on this service",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(service_total_response_bytes{ns_instance=~\"$ns_instance\",service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Average Time to First Byte",
   "type": "graph",
   "description": "Average TTFB between the NetScaler appliance and the server.  TTFB is the time interval between sending the request packet to a service and receiving the first response from the service",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "service_average_time_to_first_byte{ns_instance=~\"$ns_instance\",service=~\"$service\"}",
     "legendFormat": "Average Time to First Byte - {{service}} - {{ns_instance}}"
    }
   ]
  },
  {
   "title": "Client & Server Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "service_server_established_connections{ns_instance=~\"$ns_instance\",service=~\"$service\"}",
     "legendFormat": "Current Established Server Connections - {{service}} - {{ns_instance}}"
    },
    {
     "expr": "service_current_client_connections{ns_instance=~\"$ns_instance\",service=~\"$service\"}",
     "legendFormat": "Current Client Connections - {{service}} - {{ns_instance}}"
    },
    {
     "expr": "service_current_server_connections{ns_instance=~\"$ns_instance\",service=~\"$service\"}",
     "legendFormat": "Current Server Connections (Total) - {{service}} - {{ns_instance}}"
    }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "graph",
   "description": "Request/Response Kbps",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(service_total_request_bytes{ns_instance=~\"$ns_instance\",service=~\"$service\"}[$__interval]) * 8",
     "legendFormat": "Request Rate - {{service}} - {{ns_instance}}"
    },
    {
     "expr": "rate(service_total_response_bytes{ns_instance=~\"$ns_instance\",service=~\"$service\"}[$__interval]) * 8",
     "legendFormat": "Response Rate - {{service}} - {{ns_instance}}"
    }
   ]
  },
  {
   "title": "Requests & Responses",
   "type": "graph",
   "description": "Rate (/s) counter for total requests/responses",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(service_total_request{ns_instance=~\"$ns_instance\",service=~\"$service\"}[$__interval])",
     "legendFormat": "Request Rate - {{service}} - {{ns_instance}}"
    },
    {
     "expr": "rate(service_total_responses{ns_instance=~\"$ns_instance\",service=~\"$service\"}[$__interval])",
     "legendFormat": "Response Rate - {{service}} - {{ns_instance}}"
    }
   ]
  }
 ]
}