{
 "title": "Service Group Overview",
 "tags": [ "netscaler" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "ns_instance", "label": "NetScaler Instance", "query": "label_values(ns_instance)" },
   {
    "name": "service_group",
    "label": "Service Group",
    "query": "query_result(servicegroup_state{ns_instance=~\"$ns_instance\"})"
   },
   {
    "name": "member",
    "label": "Member",
    "query": "servicegroup_state{servicegroup=~\"$service_group\", ns_instance=~\"$ns_instance\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "description": "Current state of the service",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(servicegroup_state{ns_instance=~\"$ns_instance\",servicegroup=~\"$service_group\"}) / count(servicegroup_state{ns_instance=~\"$ns_instance\",servicegroup=~\"$service_group\"}) * 100"
    }
   ]
  },
  {
   "title": "Current Reuse Pool",
   "type": "singlestat",
   "description": "Number of requests in the idle queue/reuse pool.",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(servicegroup_current_reuse_pool{ns_instance=~\"$ns_instance\",servicegroup=~\"$service_group\"})"
    }
   ]
  },
  {
   "title": "Surge Queue",
   "type": "singlestat",
   "description": "Number of requests in the surge queue",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(servicegroup_surge_count{ns_instance=~\"$ns_instance\",servicegroup=~\"$service_group\"})"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "singlestat",
   "description": "Total number of requests received on this service",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(servicegroup_total_requests{ns_instance=~\"$ns_instance\",servicegroup=~\"$service_group\"})"
    }
   ]
  },
  {
   "title": "Total Responses",
   "type": "singlestat",
   "description": "Total number of responses received on this service",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(servicegroup_total_responses{ns_instance=~\"$ns_instance\",servicegroup=~\"$service_group\"})"
    }
   ]
  },
  {
   "title": "Total Request Bytes",
   "type": "singlestat",
   "description": "Total number of request bytes received on this service",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(servicegroup_total_request_bytes{ns_instance=~\"$ns_instance\",servicegroup=~\"$service_group\"})"
    }
   ]
  },
  {
   "title": "Total Response Bytes",
   "type": "singlestat",
   "description": "Total number of response bytes received on this service",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(servicegroup_total_response_bytes{ns_instance=~\"$ns_instance\",servicegroup=~\"$service_group\"})"
    }
   ]
  },
  {
   "title": "Client & Server Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "servicegroup_server_established_connections{ns_instance=~\"$ns_instance\",servicegroup=~\"$service_group\"}",
     "legendFormat": "Current Established Server Connections - {{member}} - {{servicegroup}} - {{ns_instance}}"
    },
    {
     "expr": "servicegroup_current_client_connections{ns_instance=~\"$ns_instance\",servicegroup=~\"$service_group\"}",
     "legendFormat": "Current Client Connections - {{member}} - {{servicegroup}} - {{ns_instance}}"
    },
    {
     "expr": "servicegroup_current_server_connections{ns_instance=~\"$ns_instance\",servicegroup=~\"$service_group\"}",
     "legendFormat": "Current Server Connections (Total) - {{member}} - {{servicegroup}} - {{ns_instance}}"
    }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "graph",
   "description": "Request/Response Kbps",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(servicegroup_total_request_bytes{ns_instance=~\"$ns_instance\",servicegroup=~\"$service_group\"}[$__interval]) * 8",
     "legendFormat": "Request Rate - {{member}} - {{servicegroup}} - {{ns_instance}}"
    },
    {
     "expr": "rate(servicegroup_total_response_bytes{ns_instance=~\"$ns_instance\",servicegroup=~\"$service_group\"}[$__interval]) * 8",
     "legendFormat": "Response Rate - {{member}} - {{servicegroup}} - {{ns_instance}}"
    }
   ]
  },
  {
   "title": "Requests & Responses",
   "type": "graph",
   "description": "Rate (/s) counter for total requests/responses",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(servicegroup_total_requests{ns_instance=~\"$ns_instance\",servicegroup=~\"$service_group\"}[$__interval])",
     "legendFormat": "Request Rate - {{member}} - {{servicegroup}} - {{ns_instance}}"
    },
    {
     "expr": "rate(servicegroup_total_responses{ns_instance=~\"$ns_instance\",servicegroup=~\"$service_group\"}[$__interval])",
     "legendFormat": "Response Rate - {{member}} - {{servicegroup}} - {{ns_instance}}"
    }
   ]
  },
  {
   "title": "Average Time to First Byte",
   "type": "graph",
   "description": "Average TTFB between the NetScaler appliance and the server.  TTFB is the time interval between sending the request packet to a service and receiving the first response from the service",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "servicegroup_average_time_to_first_byte{ns_instance=~\"$ns_instance\",servicegroup=~\"$service_group\"}",
     "legendFormat": "Average Time to First Byte - {{member}} - {{servicegroup}} - {{ns_instance}}"
    }
   ]
  }
 ]
}