{
 "title": "Virtual Server Overview",
 "tags": [ "netscaler" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ns_instance", "label": "NetScaler Instance", "query": "label_values(ns_instance)" },
   {
    "name": "virtual_server",
    "label": "Virtual Server",
    "query": "query_result(virtual_servers_active_services{ns_instance=~\"$ns_instance\"} and virtual_servers_health{virtual_server!~\".*httpredir.*$\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Health",
   "type": "singlestat",
   "description": "Percentage of UP services bound to a specific virtual server",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(virtual_servers_health{job=\"netscaler\",ns_instance=~\"$ns_instance\",virtual_server=~\"$virtual_server\"})"
    }
   ]
  },
  {
   "title": "Requests Waiting",
   "type": "singlestat",
   "description": "Number of requests waiting on a specific virtual server",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(virtual_servers_waiting_requests{job=\"netscaler\",ns_instance=~\"$ns_instance\",virtual_server=~\"$virtual_server\"})"
    }
   ]
  },
  {
   "title": "Inactive Services",
   "type": "singlestat",
   "description": "Number of inactive services bound to a specific virtual server",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(virtual_servers_inactive_services{job=\"netscaler\",ns_instance=~\"$ns_instance\",virtual_server=~\"$virtual_server\"})"
    }
   ]
  },
  {
   "title": "Active Services",
   "type": "singlestat",
   "description": "Number of active services bound to a specific virtual server",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(virtual_servers_active_services{job=\"netscaler\",ns_instance=~\"$ns_instance\",virtual_server=~\"$virtual_server\"})"
    }
   ]
  },
  {
   "title": "Total Hits",
   "type": "singlestat",
   "description": "Total virtual server hits",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(virtual_servers_total_hits{ns_instance=~\"$ns_instance\",virtual_server=~\"$virtual_server\"})"
    }
   ]
  },
  {
   "title": "Total Responses",
   "type": "singlestat",
   "description": "Total virtual server responses",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 3 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(virtual_servers_total_responses{ns_instance=~\"$ns_instance\",virtual_server=~\"$virtual_server\"})"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "singlestat",
   "description": "Total virtual server requests",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 3 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(virtual_servers_total_requests{ns_instance=~\"$ns_instance\",virtual_server=~\"$virtual_server\"})"
    }
   ]
  },
  {
   "title": "Total Response Bytes",
   "type": "singlestat",
   "description": "Total virtual server response bytes",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 3 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(virtual_servers_total_response_bytes{ns_instance=~\"$ns_instance\",virtual_server=~\"$virtual_server\"})"
    }
   ]
  },
  {
   "title": "Total Request Bytes",
   "type": "singlestat",
   "description": "Total virtual server request bytes",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(virtual_servers_total_request_bytes{ns_instance=~\"$ns_instance\",virtual_server=~\"$virtual_server\"})"
    }
   ]
  },
  {
   "title": "Hits",
   "type": "graph",
   "description": "Number of hits/second to a specific virtual server",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "hits/second" }
   ],
   "targets": [
    {
     "expr": "rate(virtual_servers_total_hits{virtual_server=~\"$virtual_server\",ns_instance=~\"$ns_instance\"}[$__interval])",
     "legendFormat": "Virtual Server Hit Rate - {{virtual_server}} - {{ns_instance}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Number of current client connections on a specific virtual server",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "none", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "virtual_servers_current_client_connections{ns_instance=~\"$ns_instance\",virtual_server=~\"$virtual_server\"}",
     "legendFormat": "Client Connections - {{virtual_server}} - {{ns_instance}}"
    },
    {
     "expr": "virtual_servers_current_server_connections{ns_instance=~\"$ns_instance\",virtual_server=~\"$virtual_server\"}",
     "legendFormat": "Server Connections - {{virtual_server}} - {{ns_instance}}"
    }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "graph",
   "description": "Request & response kbps from a specific virtual server",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(virtual_servers_total_request_bytes{virtual_server=~\"$virtual_server\",ns_instance=~\"$ns_instance\"}[$__interval]) * 8",
     "legendFormat": "Request Transfer Rate - {{virtual_server}} - {{ns_instance}}"
    },
    {
     "expr": "rate(virtual_servers_total_response_bytes{virtual_server=~\"$virtual_server\",ns_instance=~\"$ns_instance\"}[$__interval]) * 8",
     "legendFormat": "Response Transfer Rate - {{virtual_server}} - {{ns_instance}}"
    }
   ]
  },
  {
   "title": "Requests & Responses",
   "type": "graph",
   "description": "Number of requets/responses per second from a specific virtual server",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(virtual_servers_total_requests{virtual_server=~\"$virtual_server\",ns_instance=~\"$ns_instance\"}[$__interval])",
     "legendFormat": "Request Transfer Rate - {{virtual_server}} - {{ns_instance}}"
    },
    {
     "expr": "rate(virtual_servers_total_responses{virtual_server=~\"$virtual_server\",ns_instance=~\"$ns_instance\"}[$__interval])",
     "legendFormat": "Response Transfer Rate - {{virtual_server}} - {{ns_instance}}"
    }
   ]
  },
  {
   "title": "Virtual Server Health",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "virtual_servers_health{ns_instance=~\"$ns_instance\",virtual_server=~\"$virtual_server\"}",
     "legendFormat": "{{virtual_server}}"
    }
   ]
  },
  {
   "title": "Problem Virtual Servers",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "virtual_servers_health{ns_instance=~\"$ns_instance\",virtual_server=~\"$virtual_server\"} != 100"
    }
   ]
  }
 ]
}